### ISSUE TITLE
Expected result dose not match calculated result

### ISSUE THREAD

**Issue by GuyTadmor-28** [Lattice-Automation/seqfold#11]
Hi, I was just tried to work with the following example from the README file:

just returns minimum free energy
dg("GGGAGGTCGTTACATCTGGGTAACACCGGTACTGATCCGGTGACCTCCC", temp = 37.0)  # -12.94

And the result I got is -13.4 (and not -12.94 as stated in the example).
Could this be due to dependencies or something else?

Thanks

**Comment by jjtimmons** [comment]
Hey there and thanks a ton for pointing this out. The energies changed slightly a year ago, which led to this difference: https://github.com/Lattice-Automation/seqfold/commit/e400b961943d9e170a0e541d7895917cd54e1064

```
# josh at Joshuas-MacBook-Pro.local in ~/Github/seqfold/seqfold on git:master ✖︎ [19:56:28]
→ seqfold GGGAGGTCGTTACATCTGGGTAACACCGGTACTGATCCGGTGACCTCCC -t 37
-13.4
```

**Comment by jjtimmons** [comment]
fixed in https://github.com/Lattice-Automation/seqfold/commit/4a943323d4e3535102a2746bc6f2df81d3bd1410

Thanks again!
