### ISSUE TITLE
dot_bracket output length does not match sequence length

### ISSUE THREAD

**Issue by palakpsheth** [Lattice-Automation/seqfold#15]
Hello,

For the given sequence `ATATCTAGGTAGATAGCTAAGTAAATAACTACGTACATACCTCTCGGTCGATCGCTCAGTCAATCACTCCGTCCATCCCGGGGAGGGCGGAAGGACGGCAGGCCGAGAGCGAAAGAACGACAGACCGCGCAAGCACGCCAGCCCAAAACAACCACACCCCTTTTGTTTATTTCTTGGTTGATTGCTTAGTTAATTACTTC`, the output of `dot_bracket` function with temp=55, the resulting dot_bracket result: `........................................((.(((.((..((((((...........((((((.(((..........))).))))))........))))))..)).))).))` does not have the same length

**Comment by GuoYu-Peng** [comment]
Same problem: 
```python
x = "ACGCTCACCGTGCCCAGTGAGCGA"
y = seqfold.fold(x, temp=65)
print(len(x) == len(seqfold.dot_bracket(y)))
```

Output:
```python
False
```

**Comment by palakpsheth** [comment]
> Hey @palakpsheth and @GuoYu-Peng, I believe this bug should be fixed. It required changing the `dot_bracket` method to take the `seq` to get its full length

Awesome thank you
