### ISSUE TITLE
linear structure probability

### ISSUE THREAD

**Issue by ilead-cong** [Lattice-Automation/seqfold#17]
hello,
Thank you very much for the tool you developed to predict the secondary structure of a sequence. However, if we need to predict the probability of a sequence maintaining a linear structure, how should we calculate it?

ilead-cong

**Comment by jjti** [comment]
Hey @ilead-cong,

This reply is too late to be useful, but I'm now (waiting on a connecting flight) working my way thru the backlog. The probability of an oligo being a given secondary structure is a different thing than what this tool does: calculate the structure with the lowest free energy. They're related but different. This paper might be a good resource, I found this quote that matches my assumptions:

> While studies of the minimum free energy structure have proven useful, many functional RNAs, such as mRNA, are
probably not frozen in a single minimum free energy structure; rather, they exist in ensembles of secondary structures. Further, in many functional RNAs, the secondary structure changes as part of the function. One example of this is riboswitches, in which presence of a ligand causes a secondary structure change to modulate transcription, translation, or splicing (Serganov and Nudler 2013). Accurate estimates of RNA switching could also be highly useful in synthetic biology applications, where circuits can be made entirely of RNA, which serves as both a messenger and an effector (Davidson and Ellington 2007).

https://rnajournal.cshlp.org/content/early/2016/10/19/rna.053694.115.full.pdf

More info on the tool that the paper above is for: https://rna.urmc.rochester.edu/Text/ProbScan.html

I'm closing the issue (to try to clean up the backlog) but please me know if the above is unclear!
