### ISSUE TITLE
DOI for citations

### ISSUE THREAD

**Issue by kdoroschak** [Lattice-Automation/seqfold#4]
Hi! Thank you for implementing this! There is quite a lack of open source tools for energy calculations, so this fills a much-needed niche.

Would you ever consider adding a DOI to make it easier to cite?

I think this repository/package is increasingly being sought out due to a lack of python bindings for other tools, and I imagine some people would like to cite it in papers (perhaps even citing a particular release for reproducibility). If you're interested/willing, [Github makes DOI registration fairly straightforward when paired with Zenodo.](https://guides.github.com/activities/citable-code/)

**Comment by JJTimmons** [comment]
Sorry for delay but thanks for the interest in `seqfold`. I don't have admin access to the repo to enable Zenodo service, but I will ask @leshane whether we can do this

**Comment by JJTimmons** [comment]
Thank you for suggestion. I made a release of the module and added the DOI badge to the homepage:

[![DOI](https://zenodo.org/badge/224018980.svg)](https://zenodo.org/badge/latestdoi/224018980)

**Comment by JJTimmons** [comment]
PS: feels more legit already w/ the DOI. Thanks again for the interest/support of the library, lmk what you think while using it

**Comment by kdoroschak** [comment]
Thanks for adding the DOI! Not every publication allows citing packages but I'm sure some citations will start to pop up (and it's much easier to see who's using your code). So far the library has been very smooth & easy to use!
