### ISSUE TITLE
Incorrect DNA_NN values in dictionary

### ISSUE THREAD

**Issue by maxhargrea** [Lattice-Automation/seqfold#6]
Hi, I think your values are entered wrong.

Below are corrected values based on The Thermodynamics of DNA Structural Motifs
Annual Review of Biophysics and Biomolecular Structure

Vol. 33:415-440 (Volume publication date 9 June 2004)
https://doi.org/10.1146/annurev.biophys.32.110601.141800
'''
DNA_NN: BpEnergy = {
    "init": (0.2, -5.7),
    "init_G/C": (0.0, 0.0),
    "init_A/T": (2.2, 6.9),
    "sym": (0, -1.4),
    "AA/TT": (-7.6, -21.3),
    "AT/TA": (-7.2, -20.4),
    "TA/AT": (-7.2, -21.3),
    "CA/GT": (-8.5, -22.7),
    "GT/CA": (-8.4, -22.4),
    "CT/GA": (-7.8, -21.0),
    "GA/CT": (-8.2, -22.2),
    "CG/GC": (-10.6, -27.2),
    "GC/CG": (-9.8, -24.4),
    "GG/CC": (-8.0, -19.9),
}
'''

If this is not correct could you explain your values?

Thanks for putting this together! It is a great resource!

**Comment by JJTimmons** [comment]
Thanks for catching that! I changed the two differing float values and corrected the docstring to the right source https://github.com/Lattice-Automation/seqfold/commit/e400b961943d9e170a0e541d7895917cd54e1064

Should be fixed in `0.7.7`

**Comment by JJTimmons** [comment]
Lmk/re-open if there's still an issue. Also please star the package so I get dopamine
